
[rust]
debug = true
debuginfo-level = 2
backtrace = true

[term]
verbose = false
color = "auto"

# [build]
# rustflags = [
#   "-C", "link-args=-Wl,-rpath, /Library/Developer/CommandLineTools/Library/Frameworks",
# ]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]